CREATE TABLE shipments (
    shipment_id VARCHAR(64) PRIMARY KEY,
    order_id VARCHAR(64) NOT NULL UNIQUE REFERENCES orders(order_id),
    shipping_address VARCHAR(500) NOT NULL,
    carrier VARCHAR(32) NOT NULL DEFAULT 'MOCK',
    status VARCHAR(32) NOT NULL CHECK (status IN ('CREATED', 'CANCELLED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
