spring.application.name=order-service

server.address=127.0.0.1
server.port=8080

management.endpoints.web.exposure.include=health,info

spring.temporal.namespace = default
spring.temporal.connection.target = 127.0.0.1:7233

spring.temporal.workers[0].task-queue=order-fulfillment
spring.temporal.workers[0].workflow-classes[0]=com.llogistics.order_service.workflow.OrderWorkflowImpl
spring.temporal.workers[0].activity-beans[0]=orderActivities

spring.datasource.url=jdbc:postgresql://127.0.0.1:15432/logistics
spring.datasource.username=logistics
spring.datasource.password=${DB_PASSWORD:logistics_dev}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true